services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
            - "./redis/data/data_master/:/data"
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf"]

    red1:
        image: redis
        depends_on: 
            - redis
        ports:
            - "6380:6379"
        volumes:
            - "./redis/data/data_r1/:/data"
        command: [ "redis-server", "--appendonly", "yes", "--replicaof", "redis", "6379"]

    red2:
        image: redis
        depends_on: 
            - redis
        ports:
            - "6381:6379"
        volumes:
            - "./redis/data/data_r2/:/data"
        command: [ "redis-server", "--appendonly", "yes", "--replicaof", "redis", "6379"]

    redisinsight:
        image: redis/redisinsight
        ports:
            - "5540:5540"
        depends_on: 
            - redis
        
    # Exemple en passant par redis-stack qui incorpore redis-insight
    # https://hub.docker.com/r/redis/redis-stack
    # redisstack:
    #     image: redis/redis-stack
    #     ports:
    #         - "6379:6379"
    #         - "8001:8001"
    #     volumes:
    #       - "./redis/redis.conf:/redis-stack.conf"
    #       - "./redis/data/:/data"
